# Spring Datasource configuration
spring:
  datasource:
    # URL of the datasource.
    url: jdbc:hsqldb:mem:.
    # Username for the datasource.
    username: sa
    # Password for the datasource (empty in this case).
    password:
    # Driver class name for the datasource.
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    # Disables the Open Session in View pattern.
    open-in-view: false

# Actuator configuration
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

# Google Safe Browsing API configuration     
google:
  api:
    key: ${GOOGLE_API_KEY}
